HOSTS:
  ubuntu-server-1204-x64:
    roles:
      - master 
    platform: ubuntu-1204-amd64
    box: puppetlabs/ubuntu-12.04-64-nocm
    box_url: https://vagrantcloud.com/puppetlabs/boxes/ubuntu-12.04-64-nocm
    hypervisor: vagrant
  centos-70-x64:
    roles:
      - agent 
    platform: el-7-x86_64
    box: puppetlabs/centos-7.0-64-nocm
    box_url: https://vagrantcloud.com/puppetlabs/boxes/centos-7.0-64-nocm
    hypervisor : vagrant
  centos-66-x64:
    roles:
      - agent
    platform: el-6-x86_64
    box: puppetlabs/centos-6.6-64-nocm
    box_url: https://vagrantcloud.com/puppetlabs/boxes/centos-6.6-64-nocm
    hypervisor: vagrant
#  ubuntu-server-1404-x64:
#    roles:
#      - agent
#    platform: ubuntu-server-14.04-amd64
#    box: puppetlabs/ubuntu-14.04-64-nocm
#    box_url: https://vagrantcloud.com/puppetlabs/ubuntu-14.04-64-nocm
#    hypervisor: vagrant
  debian-78-x64:
    roles:
      - agent 
    platform: debian-7-amd64
    box: puppetlabs/debian-7.8-64-nocm
    box_url: https://vagrantcloud.com/puppetlabs/boxes/debian-7.8-64-nocm
    hypervisor: vagrant


CONFIG:
  log_level: verbose
  type: foss
  color: false
